### PR TITLE
Py3 fixes

### PR DESCRIPTION
**Pull request by thiblahute**
Some python3 fixes so python-phab works with python 3.4, including #32

### CODE REVIEW

**Comment by BYK** [comment]
Hey there, thanks a lot for the fixes!

Can you also fix the tests so Travis doesn't yell at us?

**Comment by thiblahute** [comment]
Passing now, sorry for not doing it before!

**Comment by BYK** [comment]
>Passing now, sorry for not doing it before!

No worries and thanks! I'll try to cut a new release this week.

**Comment by thiblahute** [comment]
> No worries and thanks! I'll try to cut a new release this week.

Perfect thanks :)

**Pull request merged**
