### PR TITLE
Allow for nested methods to support conduit calls such as diffusion.repository.edit

### PR DESCRIPTION
**Pull request by jamesmeador**
Phabricator has introduced some API methods that go beyond just an application name and method name. This minor change supports those methods in a non-breaking way.

### CODE REVIEW

**Comment by bizrad6** [comment]
+1

**Comment by BYK** [comment]
Hey, thanks!

Can you squash your commits into one and add a test case for this new thing?

**Comment by BYK** [comment]
Also adding `Fixes #38` to your commit message and PR description would be great?

**Comment by jamesmeador** [comment]
Thanks for the tips; this should be finished upon travis completion.

Note: I had to update interfaces.json to provide some valid endpoints to test against.

**Comment by BYK** [comment]
Awesome, thanks!

**Pull request merged**
